# Generated by Django 3.2.3 on 2021-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
                ('employment_title', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('brief_description', models.TextField()),
                ('linkedIn', models.URLField()),
            ],
        ),
    ]
