# Generated by Django 3.2.3 on 2021-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
