# Generated by Django 3.2.3 on 2021-05-26 15:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_carddetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>'),
        ),
    ]
