# Generated by Django 3.2.3 on 2021-05-27 07:38

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20210527_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='first_name'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='uuid',
            field=models.UUIDField(verbose_name=uuid.uuid4),
        ),
    ]
