# Generated by Django 3.2.3 on 2021-05-27 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20210527_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each card'),
        ),
    ]
