FROM python:3.8


# Environment Variables

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /code


# install dependencies

COPY Pipfile Pipfile.lock /code/

RUN pip install pipenv && pipenv install --system


# copy project 


COPY . /code/